title: colin.bot
description: >-
  Adventures in cybersecurity, ethical hacking, and digital mischief. Home of clever tools, 
  insightful stories, and occasional sarcasm from the frontlines of tech.

baseurl: "" 
url: "https://colin.bot"
twitter_username: cybercdh
github_username:  cybercdh

theme: minima
plugins:
  - jekyll-feed

google_analytics: G-JHQ35THLPX

# Ensure posts dated slightly in the future still publish
future: true
# Optionally set site timezone for date handling
timezone: Europe/London
 
